// <auto-generated />
using System;
using GroupSoftware.Repository;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GroupSoftware.Repository.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20201015113351_First")]
    partial class First
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("GroupSoftware.Repository.Entities.Cliente", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnName("id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnName("data-cadastro")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnName("nome")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("Status")
                        .HasColumnName("status")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Cliente");
                });

            modelBuilder.Entity("GroupSoftware.Repository.Entities.Pedido", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnName("id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnName("data-cadastro")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("IdCliente")
                        .HasColumnName("idCliente")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ProdutoPedidoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("StatusEntrega")
                        .IsRequired()
                        .HasColumnName("status-entrega")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IdCliente");

                    b.HasIndex("ProdutoPedidoId");

                    b.ToTable("Pedido");
                });

            modelBuilder.Entity("GroupSoftware.Repository.Entities.Produto", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnName("id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Disponivel")
                        .HasColumnName("disponivel")
                        .HasColumnType("bit");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnName("nome")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<Guid?>("ProdutoPedidoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("Valor")
                        .HasColumnName("valor")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("ProdutoPedidoId");

                    b.ToTable("Produto");
                });

            modelBuilder.Entity("GroupSoftware.Repository.Entities.ProdutoPedido", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnName("id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdProduto")
                        .HasColumnName("idProduto")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantidade")
                        .HasColumnName("quantidade")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ProdutoPedido");
                });

            modelBuilder.Entity("GroupSoftware.Repository.Entities.Pedido", b =>
                {
                    b.HasOne("GroupSoftware.Repository.Entities.Cliente", "Cliente")
                        .WithMany("Pedido")
                        .HasForeignKey("IdCliente")
                        .HasConstraintName("pedido_fk")
                        .IsRequired();

                    b.HasOne("GroupSoftware.Repository.Entities.ProdutoPedido", "ProdutoPedido")
                        .WithMany()
                        .HasForeignKey("ProdutoPedidoId");
                });

            modelBuilder.Entity("GroupSoftware.Repository.Entities.Produto", b =>
                {
                    b.HasOne("GroupSoftware.Repository.Entities.ProdutoPedido", null)
                        .WithMany("Produto")
                        .HasForeignKey("ProdutoPedidoId");
                });
#pragma warning restore 612, 618
        }
    }
}
